### ISSUE TITLE
Parse.EnumerateInput?

### ISSUE THREAD

**Issue by Mike-E-angelo** [IanWold/SpracheJSON#1]
In your JSON parser code, there appears to be a call to `Parse.EnumerateInput` that no longer appears to be found in the Sprache library, and I was curious if you had its current corollary.

**Comment by IanWold** [comment]
Thank you for the question! I wrote Parse.EnumerateInput myself (I hadn't realized that it snuck it's way into this code). I'll go searching for that code, and then I'll update the JSON parser here so that it doesn't assume the Sprache library uses it.

**Comment by IanWold** [comment]
Here's the EnumerateInput function I added to Parse.cs:

```c#
		/// <summary>
		/// Parses each value in input with parser, returning the result of the first successful parse, if any.
		/// </summary>
		/// <typeparam name="T"></typeparam>
		/// <typeparam name="U"></typeparam>
		/// <param name="input"></param>
		/// <param name="parser"></param>
		/// <returns></returns>
		public static Parser<U> EnumerateInput<T, U>(T[] input, Func<T, Parser<U>> parser)
		{
			if (input == null || input.Length == 0) throw new ArgumentNullException("input");
			if (parser == null) throw new ArgumentNullException("parser");

			return i =>
			{
				var res = (IResult<U>)(new Result<U>(null, null, null));
				foreach (var inp in input)
				{
					res = parser(inp)(i);
					if (res.WasSuccessful) return res;
				}

				return res;
			};
		}
```

**Comment by IanWold** [comment]
I updated the parser here, and I included EnumerateInput in the JSON parser directly!

**Comment by Mike-E-angelo** [comment]
Great, thank you so much!

**Comment by IanWold** [comment]
Sure thing; thanks much for raising the issue, it had slipped past me.

**Comment by alyonatischenko** [comment]
~~_**
### 
### 
### ~~~~_**** _ ~~ ~~ ** _ ~~

**Comment by Mike-E-angelo** [comment]
![](https://media.giphy.com/media/Rt23MIHkCJwdy/giphy.gif)
